# Generated by Django 5.2.7 on 2025-10-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_image_movie_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='total_episodes',
            field=models.IntegerField(default=1),
        ),
    ]
